### PR TITLE
Explain AntiFeatures

### PR DESCRIPTION
**Pull request by licaon-kter**
Ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2662

I see that Analytics functions [are gutted](https://github.com/lbryio/lbry-fdroid/blob/master/app/src/main/java/io/lbry/browser/utils/LbryAnalytics.java#L31), but all the rest?

https://lbry.com/faq/privacy-and-data does not have a link to the F-Droid saying it is any different, also https://github.com/lbryio/lbry-fdroid/issues/15 doesn't make it clearer either.

### CODE REVIEW

**Comment by kekkyojin** [comment]
Hi, @licaon-kter .Thank you for creating this PR yourself in order to "fix" an issue created on GitLab.

I could accept adding the "tracking" section, although LBRY is no longer providing the benefits which required users being "tracked" and verified. However, that code has not being changed, yet -it has been on LBRY Desktop-. As I said, yes, I could approve that change, if LBRY team is ok with it.

However, I don't see why connecting to LBRY.com is considered "nonfreenetwork". Could you explain that?

From my part, LBRY FDroid is the same that LBRY Android, but with Firebase removed. It also had turned off a feature that logged buffering events to a remote server.

**Comment by licaon-kter** [comment]
The app depends on some server, the user can't change it.

NonFreeNet covers many cases, we know it should be split to make it more a specific AF, eg. Free server vs Free to change server in app, etc

**Comment by kekkyojin** [comment]
Those flags had been added to FDroid metadata YAML file. I merge these changes so there is an explanation for why the app is flagged. Don’t know if the documentation on FDroid store will be updated, so description there could be outdated from this merged change.

Thanks, @licaon-kter for the PR and the patience.

**Comment by licaon-kter** [comment]
Next app update will update the descriptions too.

**Pull request merged**
